name: release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: |
          pwd
          ls
      - name: Build
        run: |
          cd TestGithubActions
          dotnet publish -r linux-x64
          dotnet publish -r win-x64
          dotnet publish -r osx-x64
      - name: tree on publish
        run: tree ./bin/Release/netcoreapp3.1/publish