name: release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.deotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      - name: pwd
        run: pwd
      - name: ls
        run: ls -alF
      - name: Build linux-x64
        run: dotnet publish --framework netcoreapp3.1 --runtime linux-x64 -c Release --self-contained
      - name: Build win-x64
        run: dotnet publish --framework netcoreapp3.1 --runtime win-x64 -c Release --self-contained
      - name: Build osx-x64
        run: dotnet publish --framework netcoreapp3.1 --runtime osx-x64 -c Release --self-contained
      - name: tree on publish
        run: tree ./TestGithubActions/bin/Release/netcoreapp3.1/publish