name: release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Root Dir
        run: ls -alF
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            README.md