name: release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          dotnet publish --os linux-x64
          dotnet publish --os win-x64
          dotnet publish --os osx-x64
      - name: tree on publish
        run: tree ./TestGithubActions/bin/Release/netcoreapp3.1/publish